#!/usr/bin/env python3
"""FDE Impromptu Coach - command line entry point.

Daily impromptu-speaking practice for the Forward Deployed Engineer role:
5 fresh questions in a Calibri/blue PowerPoint deck (60 s per slide, auto-advance),
recorded with QuickTime, uploaded to YouTube as a private video, with a streak
protected by escalating reminders. Two audio practices read verbatim passages
from free public-domain books: pronunciation (pen method) and legato
(smooth, connected speech).

Run `fde_coach.py --help` for commands. Python 3.9+.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fdecoach import __version__  # noqa: E402
from fdecoach.config import APP_NAME, ENTRY_SCRIPT, SKILL_DIR, Paths, load_config, parse_hhmm, save_config  # noqa: E402


def _ctx(args):
    from fdecoach.app import Ctx
    return Ctx(verbose=getattr(args, "verbose", False))


def _print(obj) -> None:
    print(json.dumps(obj, indent=2, ensure_ascii=False))


def _sh(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _chmod_x(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


# --------------------------------------------------------------------------- commands

def cmd_setup(args) -> int:
    from fdecoach import questions, scheduler
    from fdecoach.state import Runtime
    ctx = _ctx(args)
    paths, cfg = ctx.paths, ctx.cfg
    claude = questions.resolve_claude(cfg)
    if claude and not cfg.get("claude_path"):
        cfg["claude_path"] = claude
    if args.time:
        parse_hhmm(args.time)
        cfg["daily_time"] = args.time
    save_config(paths, cfg)

    paths.bin_dir.mkdir(parents=True, exist_ok=True)
    wrapper = paths.bin_dir / "fde-coach"
    wrapper.write_text(
        "#!/bin/bash\n"
        f"# {APP_NAME} launcher (generated by setup)\n"
        f"export FDE_COACH_HOME={_sh(str(paths.root))}\n"
        f"exec {_sh(sys.executable)} {_sh(str(ENTRY_SCRIPT))} \"$@\"\n", encoding="utf-8")
    _chmod_x(wrapper)
    paths.start_command.write_text(
        "#!/bin/bash\n"
        f"# Double-click to record today's {APP_NAME} session.\n"
        f"{_sh(str(wrapper))} session\n"
        "echo\n"
        "echo \"Done. You can close this window.\"\n", encoding="utf-8")
    _chmod_x(paths.start_command)

    rt = Runtime(paths)
    rt.data["warmup_pending"] = not args.no_warmup
    rt.save()
    print(f"{APP_NAME} {__version__}")
    print(f"  data folder   : {paths.root}")
    print(f"  recordings    : {paths.recordings_dir(cfg, create=False)}")
    print(f"  claude CLI    : {claude or 'NOT FOUND - questions will come from the built-in bank'}")
    print(f"  launcher      : {wrapper}")
    print(f"  double-click  : {paths.start_command}")
    if not args.no_agents:
        # Agent reinstall is a fresh start: clear old error output so doctor
        # does not keep reporting errors from a previous install.
        for err_log in paths.logs.glob("*.err.log"):
            err_log.write_text("", encoding="utf-8")
        for line in scheduler.install(cfg, paths):
            print(f"  launchd       : {line}")
        print(f"  schedule      : daily at {cfg['daily_time']}, reminder checks every 15 minutes")
    return 0


def cmd_daily(args) -> int:
    from fdecoach import app
    res = app.daily(_ctx(args))
    _print(res)
    return 0 if res.get("ok") else 1


def cmd_session(args) -> int:
    from fdecoach import app
    ctx = _ctx(args)
    if args.detach:
        app.spawn_detached(["session"] + (["--force"] if args.force else []))
        print("Practice session started in the background: QuickTime recording + slide show "
              "(about 5 minutes). Check progress with: fde-coach status")
        return 0
    res = app.run_session(ctx, force=args.force)
    _print(res)
    return 0 if res.get("ok") else 1


def cmd_remind(args) -> int:
    from fdecoach import app
    print(app.remind(_ctx(args)))
    return 0


def cmd_generate(args) -> int:
    from fdecoach import app, macos
    ctx = _ctx(args)
    session, created = app.ensure_today(ctx, source=args.source, replace=args.replace, brief=args.brief or "")
    info = {
        "date": session["date"], "day_number": session["day_number"], "level": session["level"],
        "source": session["source"], "created": created, "deck": session["deck_path"],
        "categories": [f"{q.get('category_label')} (D{q.get('difficulty')})" for q in session["questions"]],
        "notes": session.get("notes", []),
        "questions": [q["text"] for q in session["questions"]] if args.reveal
        else "hidden to keep the surprise (see them after recording: fde-coach history)",
    }
    _print(info)
    if args.open:
        macos.powerpoint_open(Path(session["deck_path"]), ctx.cfg.get("presentation_app"))
    return 0


def cmd_plan(args) -> int:
    from fdecoach import app
    _print(app.authoring_plan(_ctx(args)))
    return 0


def cmd_build(args) -> int:
    from fdecoach import app
    ctx = _ctx(args)
    session, _ = app.ensure_today(ctx, questions_path=Path(args.questions).expanduser(), replace=args.replace)
    _print({"date": session["date"], "deck": session["deck_path"], "source": session["source"],
            "rejected_and_replaced_from_bank": session.get("notes", [])})
    return 0


def cmd_open(args) -> int:
    from fdecoach import app, macos
    ctx = _ctx(args)
    session, _ = app.ensure_today(ctx)
    macos.powerpoint_open(Path(session["deck_path"]), ctx.cfg.get("presentation_app"))
    print(session["deck_path"])
    return 0


def cmd_status(args) -> int:
    from fdecoach import app
    st = app.status(_ctx(args))
    if args.json:
        _print(st)
        return 0
    s = st["streak"]
    print(f"Streak: {s['current']} day(s)  |  best {s['best']}  |  total sessions {s['total']}  |  level {st['level']}/5")
    pron = st.get("pronunciation")
    if pron:
        ps = pron["streak"]
        print(f"Pronunciation: {ps['current']} day(s)  |  best {ps['best']}  |  total {ps['total']}  |  "
              f"due words: {', '.join(pron['due_words']) or '-'}")
    leg = st.get("legato")
    if leg:
        ls = leg["streak"]
        state = "off" if not leg.get("enabled", True) else (
            "recorded today" if (leg.get("today") or {}).get("recorded") else "not recorded today")
        print(f"Legato: {ls['current']} day(s)  |  best {ls['best']}  |  total {ls['total']}  |  "
              f"flow level {leg.get('next_flow_level', 1)}/3  |  {state}")
    t = st["today"]
    if not t:
        print(f"Today ({st['date']}): no deck yet")
    else:
        state = "RECORDED" if t["recorded"] else "NOT RECORDED YET"
        print(f"Today ({st['date']}): Day {t['day_number']}  |  {state}  |  questions from {t['source']}")
        print(f"  deck : {t['deck']}")
        if t.get("video"):
            print(f"  video: {t['video']}")
        if t["recorded"]:
            yt = t.get("youtube") or {}
            print(f"  youtube: {yt.get('url') or yt.get('status')}")
    if st["next_reminder"]:
        extra = f" (snoozed until {st['snooze_until']})" if st["snooze_until"] else ""
        print(f"Next reminder: {st['next_reminder']}{extra}")
    if st["pending_uploads"]:
        print(f"Pending uploads: {', '.join(st['pending_uploads'])}")
    print(f"YouTube connected: {'yes' if st['youtube_configured'] else 'no (run: fde-coach youtube-auth)'}")
    if not st["calendar_configured"]:
        print("Google Calendar alerts: not connected (run: fde-coach calendar-auth)")
    elif st["calendar_today"]:
        state = {"created": "armed - alerts fire if you don't record",
                 "deleted": "cleared - recorded"}.get(st["calendar_today"], st["calendar_today"])
        print(f"Google Calendar alert today: {state}")
    print("Scheduler: " + ", ".join(f"{k.split('.')[-1]}={'on' if v else 'OFF'}" for k, v in st["agents"].items()))
    return 0


def cmd_history(args) -> int:
    from fdecoach import app
    rows = app.history_rows(_ctx(args), limit=args.limit, reveal_today=args.reveal)
    if args.json:
        _print(rows)
        return 0
    if not rows:
        print("No sessions yet.")
    for r in rows:
        mark = "\u2713" if r["recorded"] else "\u2717"
        print(f"{mark} {r['date']}  Day {r['day']}  L{r['level']}  youtube: {r['youtube']}  feedback: {r['feedback'] or '-'}")
        for q in r["questions"]:
            print(f"     - {q}")
    return 0


def cmd_complete(args) -> int:
    from fdecoach import app
    s = app.complete_manually(_ctx(args), Path(args.video) if args.video else None,
                              no_video=args.no_video, note=args.note or "")
    print(f"Marked {s.get('date')} as recorded ({s.get('video_path') or 'no video'}).")
    return 0


def cmd_upload(args) -> int:
    from fdecoach import app
    for line in app.upload_pending(_ctx(args), interactive=True):
        print(line)
    return 0


def cmd_youtube_auth(args) -> int:
    from fdecoach import app, youtube
    ctx = _ctx(args)
    print(youtube.authorize(ctx.paths))
    for line in app.upload_pending(ctx, interactive=True):
        print(line)
    return 0


def cmd_calendar_auth(args) -> int:
    from fdecoach import app, gcal
    ctx = _ctx(args)
    print(gcal.authorize(ctx.paths))
    for line in app.calendar_sync_all(ctx):
        print(line)
    return 0


def cmd_calendar_sync(args) -> int:
    from fdecoach import app
    for line in app.calendar_sync_all(_ctx(args), clear=args.clear):
        print(line)
    return 0


def cmd_doctor(args) -> int:
    from fdecoach import app, gcal, macos, questions, scheduler, youtube
    from fdecoach.state import Runtime
    ctx = _ctx(args)
    cfg, paths = ctx.cfg, ctx.paths
    problems = []

    def line(good: bool, label: str, detail: str = "") -> None:
        if not good:
            problems.append(label)
        print(f"[{'ok' if good else '!!'}] {label}{': ' + detail if detail else ''}")

    line(sys.version_info >= (3, 9), "Python", f"{sys.version.split()[0]} ({sys.executable})")
    for mod in ("pptx", "lxml", "googleapiclient", "google_auth_oauthlib"):
        try:
            __import__(mod)
            line(True, f"Python module {mod}")
        except ImportError:
            line(False, f"Python module {mod}", "missing - re-run install.sh")
    claude = questions.resolve_claude(cfg)
    if claude:
        try:
            ver = subprocess.run([claude, "--version"], capture_output=True, text=True, timeout=30).stdout.strip()
        except Exception as exc:  # noqa: BLE001
            ver = f"not runnable ({exc})"
        line(True, "Claude Code CLI", f"{claude} {ver}")
    else:
        line(False, "Claude Code CLI", "not found; set claude_path (the built-in bank still works)")
    line(macos.is_macos() or macos.dry_run(), "macOS", os.uname().sysname)
    line(macos.app_exists(cfg.get("presentation_app", "Microsoft PowerPoint")), "Microsoft PowerPoint installed")
    line(macos.app_exists("QuickTime Player"), "QuickTime Player installed")
    from fdecoach import audio
    line(audio.has_ffmpeg(), "ffmpeg (pronunciation video)",
         "found" if audio.has_ffmpeg() else "not found - pronunciation videos are skipped, audio is kept "
         "(brew install ffmpeg)")
    want_device = str(cfg.get("pronunciation", {}).get("audio_device", ""))
    devices = audio.avfoundation_audio_devices() if audio.has_ffmpeg() else []
    resolved = audio.resolve_audio_device(want_device) if devices else None
    line(bool(resolved is not None or not devices), "Pronunciation audio input",
         f"{devices[resolved][1] if resolved is not None and devices else want_device or 'first available'}"
         if devices else "dry-run or no ffmpeg")
    if not macos.dry_run() and macos.is_macos():
        ok_audio = macos.quicktime_audio_check()
        line(ok_audio, "QuickTime audio recording",
             "works" if ok_audio else "blocked - approve the microphone prompt (doctor --warmup)")
    else:
        line(True, "QuickTime audio recording", "dry-run")
    cam, mic = macos.has_camera(), macos.has_microphone()
    if cfg.get("recording", {}).get("mode") == "none":
        line(True, "Camera & microphone", "not needed (recording.mode=none: deck show only, no video)")
    else:
        line(cam and mic, "Camera & microphone",
             "found" if cam and mic else
             "not found - run sessions on a Mac with a camera, make camera-less practice the default "
             "(config --set recording.mode=none), or practise and mark the day: fde-coach complete --no-video")
    try:
        from fdecoach import library
        built, mine = len(library.builtin()), len(library.user_passages(paths))
        line(built > 0, "Passage library (public-domain books)", f"{built} built-in + {mine} imported")
    except Exception as exc:  # noqa: BLE001
        line(False, "Passage library (public-domain books)", f"unreadable: {exc}")
    rec = paths.recordings_dir(cfg, create=False)
    if rec.exists():
        free = shutil.disk_usage(str(rec)).free / 1e9
        line(os.access(str(rec), os.W_OK) and free > 2, "Recordings folder", f"{rec} ({free:.0f} GB free)")
    else:
        line(False, "Recordings folder", f"{rec} does not exist yet (created on first session)")
    for label, loaded in scheduler.status().items():
        line(loaded, f"launchd agent {label}", "loaded" if loaded else "not loaded - run: fde-coach install-agents")
        # A loaded agent can still fail on every tick (e.g. macOS TCC blocks
        # launchd from reading the script); surface the last logged error.
        err = paths.logs / f"{label.split('.')[-1]}.err.log"
        if err.exists() and time.time() - err.stat().st_mtime < 86400:
            # agent stderr also carries INFO lines; only real errors matter
            errors = [l for l in err.read_text(encoding="utf-8", errors="replace").splitlines()
                      if ("ERROR" in l or "Traceback" in l or "Errno" in l)]
            if errors:
                msg = errors[-1]
                line(False, f"agent {label} error log", msg[:120] + ("…" if len(msg) > 120 else ""))
    if cfg.get("youtube", {}).get("enabled", True):
        line(paths.client_secret.exists(), "YouTube OAuth client file", str(paths.client_secret))
        configured = youtube.is_configured(paths)
        line(configured, "YouTube authorized", "yes" if configured else "run: fde-coach youtube-auth")
    gc = cfg.get("google_calendar", {})
    if gc.get("enabled", True):
        connected = gcal.is_configured(paths)
        line(connected, "Google Calendar missed-practice alerts",
             f"on (event {gc.get('event_time')}, alerts {', '.join(gc.get('popup_times') or [])})" if connected
             else "run: fde-coach calendar-auth")
    rt = Runtime(paths)
    if rt.data.get("warmup_results"):
        print(f"     background permission check ({rt.data.get('warmup_at')}): " + "; ".join(rt.data["warmup_results"]))
    if args.warmup:
        print("Permission warm-up from this terminal (click OK/Allow on every macOS prompt):")
        for r in app.run_warmup(ctx):
            print("   " + r)
        app.update_runtime(ctx, lambda r: r.data.update(warmup_pending=True))
        scheduler.kickstart(scheduler.REMIND_LABEL)
        print("Also triggered the background agent so macOS asks for its own permissions now - approve those too.")
    log_file = paths.logs / "fde_coach.log"
    if log_file.exists():
        tail = log_file.read_text(encoding="utf-8", errors="ignore").splitlines()[-400:]
        errors = [ln for ln in tail if " ERROR " in ln or " WARNING " in ln]
        if errors:
            print("Recent warnings/errors:")
            for ln in errors[-8:]:
                print("   " + ln[:220])
    print("All good." if not problems else f"{len(problems)} item(s) need attention.")
    return 0 if not problems else 1


def cmd_install_agents(args) -> int:
    from fdecoach import scheduler
    ctx = _ctx(args)
    for line in scheduler.install(ctx.cfg, ctx.paths):
        print(line)
    return 0


def cmd_uninstall_agents(args) -> int:
    from fdecoach import scheduler
    for line in scheduler.uninstall():
        print(line)
    return 0


def _coerce(value: str):
    try:
        return json.loads(value)
    except ValueError:
        return value


def cmd_config(args) -> int:
    from fdecoach import scheduler
    _ctx(args)
    paths = Paths()
    user = json.loads(paths.config.read_text(encoding="utf-8")) if paths.config.exists() else {}
    if args.set:
        reinstall = False
        for item in args.set:
            key, sep, raw = item.partition("=")
            if not key or not sep:
                print(f"bad --set {item!r}; use key=value (dotted keys for nested values, JSON for lists/bools)")
                return 2
            value = _coerce(raw)
            if key == "daily_time" or key.endswith(".daily_time"):
                parse_hhmm(str(value))
                reinstall = True
            node = user
            parts = key.split(".")
            for part in parts[:-1]:
                node = node.setdefault(part, {})
            node[parts[-1]] = value
        save_config(paths, user)
        print("Saved.")
        if reinstall:
            for line in scheduler.install(load_config(paths), paths):
                print(line)
    _print(load_config(paths))
    return 0


def cmd_level(args) -> int:
    from fdecoach import app
    from fdecoach.state import level_for, today
    ctx = _ctx(args)

    def change(rt) -> None:
        cur = 0 if args.reset else int(rt.data.get("level_adjust", 0)) + (1 if args.up else -1 if args.down else 0)
        rt.data["level_adjust"] = max(-4, min(4, cur))

    if args.up or args.down or args.reset:
        app.update_runtime(ctx, change)
    lvl = level_for(ctx.history(), ctx.cfg, ctx.runtime(), today())
    print(f"Level for the next new deck: {lvl} of 5 (manual adjustment {int(ctx.runtime().data.get('level_adjust', 0)):+d}). "
          "An existing deck keeps its level unless you run: fde-coach generate --replace")
    return 0


def cmd_pronounce(args) -> int:
    from fdecoach import app, pronounce_session
    ctx = _ctx(args)
    if args.pron_command == "session":
        if args.detach:
            app.spawn_detached(["pronounce", "session"] + (["--force"] if args.force else []))
            print("Pronunciation session started in the background: QuickTime audio + slide show "
                  "(about 5 minutes). Check progress with: fde-coach pronounce status")
            return 0
        res = pronounce_session.run_session(ctx, force=args.force)
        _print(res)
        return 0 if res.get("ok") else 1
    if args.pron_command == "daily":
        _print(pronounce_session.daily(ctx))
        return 0
    if args.pron_command == "generate":
        opts = {"passage_id": args.passage} if args.passage else {}
        session, created = pronounce_session.ensure_today(ctx, replace=args.replace, **opts)
        info = {"date": session["date"], "day_number": session["day_number"], "source": session["source"],
                "created": created, "deck": session["deck_path"],
                "words": session["words"], "notes": session.get("notes", []),
                "paragraph": session["paragraph"] if args.reveal
                else "hidden until you record (fde-coach pronounce history --reveal)"}
        if session.get("passage"):
            from fdecoach.library import credit_line
            info["passage"] = credit_line(session["passage"])
        _print(info)
        return 0
    if args.pron_command == "status":
        st = pronounce_session.status(ctx)
        if args.json:
            _print(st)
            return 0
        s = st["streak"]
        print(f"Pronunciation streak: {s['current']} day(s)  |  best {s['best']}  |  "
              f"total {s['total']}  |  due words: {', '.join(st['due_words']) or '-'}")
        t = st["today"]
        if not t:
            print(f"Today ({st['date']}): no deck yet (built at the pronunciation daily run)")
        else:
            state = "RECORDED" if t["recorded"] else "NOT RECORDED YET"
            print(f"Today: Day {t['day_number']}  |  {state}  |  words: {', '.join(t.get('words') or [])}")
            if t.get("passage"):
                print(f"  passage: {t['passage']}")
            if t.get("audio"):
                print(f"  audio: {t['audio']}")
            if t["recorded"]:
                yt = t.get("youtube") or {}
                print(f"  youtube: {yt.get('url') or yt.get('status')}")
        if st["pending_uploads"]:
            print(f"Pending uploads: {', '.join(st['pending_uploads'])}")
        return 0
    if args.pron_command == "history":
        rows = pronounce_session.history_rows(ctx, limit=args.limit, reveal_today=args.reveal)
        if args.json:
            _print(rows)
            return 0
        if not rows:
            print("No pronunciation sessions yet.")
        for r in rows:
            mark = "✓" if r["recorded"] else "✗"
            print(f"{mark} {r['date']}  Day {r['day']}  youtube: {r['youtube']}  words: {', '.join(r['words'])}")
            if r.get("passage"):
                print(f"     — {r['passage']}")
            print(f"     {r['paragraph']}")
        return 0
    if args.pron_command == "words":
        from fdecoach.config import save_config
        if args.add:
            words = [w.strip().lower() for w in args.add if w.strip()]
            user = json.loads(ctx.paths.config.read_text(encoding="utf-8")) if ctx.paths.config.exists() else {}
            have = [w.lower() for w in user.get("pronunciation", {}).get("words", [])]
            user.setdefault("pronunciation", {})["words"] = have + [w for w in words if w not in have]
            save_config(ctx.paths, user)
            print(f"Added: {', '.join(words)}")
        if args.remove:
            user = json.loads(ctx.paths.config.read_text(encoding="utf-8")) if ctx.paths.config.exists() else {}
            gone = [w.strip().lower() for w in args.remove]
            pron_list = user.get("pronunciation", {}).get("words", [])
            user.setdefault("pronunciation", {})["words"] = [w for w in pron_list if w.lower() not in gone]
            save_config(ctx.paths, user)
            print(f"Removed: {', '.join(gone)}")
        st = pronounce_session.status(ctx)
        print("Words:", ", ".join(st["all_words"]) or "(none yet — add with: fde-coach pronounce words --add WORD)")
        print("Due today:", ", ".join(st["due_words"]) or "-")
        return 0
    if args.pron_command == "upload":
        for line in pronounce_session.upload_pending(ctx, interactive=True):
            print(line)
        return 0
    return 2


def cmd_legato(args) -> int:
    from fdecoach import app, legato_session
    from fdecoach.library import credit_line
    ctx = _ctx(args)
    c = args.leg_command
    if c == "session":
        if args.detach:
            app.spawn_detached(["legato", "session"] + (["--force"] if args.force else []))
            print("Legato session started in the background: audio recording + slide show "
                  "(about 5 minutes). Check progress with: fde-coach legato status")
            return 0
        res = legato_session.run_session(ctx, force=args.force)
        _print(res)
        return 0 if res.get("ok") else 1
    if c == "daily":
        _print(legato_session.daily(ctx))
        return 0
    if c == "generate":
        session, created = legato_session.ensure_today(ctx, replace=args.replace, passage_id=args.passage)
        _print({"date": session["date"], "day_number": session["day_number"], "created": created,
                "deck": session["deck_path"], "passage": credit_line(session.get("passage") or {}),
                "passage_id": session.get("passage_id"), "flow_level": session.get("flow_level"),
                "linking_drill": len(session.get("chains") or []), "notes": session.get("notes", []),
                "paragraph": session["paragraph"] if args.reveal
                else "hidden until you record (fde-coach legato history --reveal)"})
        return 0
    if c == "status":
        st = legato_session.status(ctx)
        if args.json:
            _print(st)
            return 0
        s = st["streak"]
        print(f"Legato streak: {s['current']} day(s)  |  best {s['best']}  |  total {s['total']}  |  "
              f"next flow level {st.get('next_flow_level', 1)}/3")
        if not st.get("enabled", True):
            print("Legato practice is off (turn on: fde-coach config --set legato.enabled=true)")
        t = st["today"]
        if not t:
            print(f"Today ({st['date']}): no deck yet (built at the legato daily run, or: fde-coach legato generate)")
        else:
            state = "RECORDED" if t["recorded"] else "NOT RECORDED YET"
            print(f"Today: Day {t['day_number']}  |  {state}  |  passage: {t.get('passage') or '-'}")
            if t.get("audio"):
                print(f"  audio: {t['audio']}")
            if t["recorded"]:
                yt = t.get("youtube") or {}
                print(f"  youtube: {yt.get('url') or yt.get('status')}")
        if st["pending_uploads"]:
            print(f"Pending uploads: {', '.join(st['pending_uploads'])}")
        return 0
    if c == "history":
        rows = legato_session.history_rows(ctx, limit=args.limit, reveal_today=args.reveal)
        if args.json:
            _print(rows)
            return 0
        if not rows:
            print("No legato sessions yet.")
        for r in rows:
            mark = "\u2713" if r["recorded"] else "\u2717"
            print(f"{mark} {r['date']}  Day {r['day']}  flow L{r.get('flow_level') or '-'}  "
                  f"feedback: {r.get('feedback') or '-'}  youtube: {r['youtube']}")
            print(f"     — {r.get('passage') or ''}")
            print(f"     {r['paragraph']}")
        return 0
    if c == "upload":
        for line in legato_session.upload_pending(ctx, interactive=True):
            print(line)
        return 0
    return 2


def cmd_library(args) -> int:
    from fdecoach import library
    ctx = _ctx(args)
    c = args.lib_command
    if c == "list":
        items = library.all_passages(ctx.paths)
        if args.theme:
            items = [p for p in items if p.get("theme") == args.theme]
        if args.level:
            items = [p for p in items if int(p.get("level", 0)) == args.level]
        if args.mine:
            items = [p for p in items if p.get("origin") == "user"]
        if args.json:
            _print([{k: v for k, v in p.items() if k != "text"} for p in items])
            return 0
        for p in items:
            print(f"{p['id']:28} L{p.get('level', '?')} {p.get('words', 0):4}w  {p.get('theme', ''):10} "
                  f"{library.credit_line(p, short=True)}")
        themes = sorted({p.get("theme", "") for p in library.all_passages(ctx.paths)})
        print(f"\n{len(items)} passage(s). Themes: {', '.join(themes)}. "
              "Levels: 1 short sentences, 2 medium, 3 long winding sentences.")
        return 0
    if c == "show":
        p = library.get(ctx.paths, args.id)
        if p is None:
            print(f"No passage {args.id!r}. See: fde-coach library list")
            return 1
        src = p.get("source") or {}
        print(library.credit_line(p))
        print(f"{src.get('name', '')}  {src.get('url', '')}  ({src.get('license', '')})")
        print(f"{p.get('words')} words  |  level {p.get('level')}  |  theme {p.get('theme')}\n")
        print(p["text"])
        words = (p.get("pronunciation") or {}).get("target_words") or []
        if words:
            print("\nPronunciation targets: " + ", ".join(f"{t['word']} ({t.get('stress', '')})" for t in words))
        return 0
    if c == "import-gutenberg":
        res = library.import_gutenberg(ctx.paths, args.book_id, max_n=args.max, theme=args.theme or "",
                                       year=args.year)
        print(f"{res['title'] or 'Book ' + str(args.book_id)} — {res['author'] or 'unknown author'}: "
              f"{res['added']} passage(s) added, {res['skipped']} already in the library "
              f"({res['candidates']} readable paragraphs picked). Saved in {res['library_file']}")
        if res["added"]:
            print("They join the rotation for legato (and pronunciation, once Claude has marked up their hard words).")
        return 0
    if c == "import-file":
        res = library.import_file(ctx.paths, Path(args.path), author=args.author, title=args.title, year=args.year,
                                  url=args.url or "", theme=args.theme or "", max_n=args.max)
        print(f"{res['title']} — {res['author']}: {res['added']} passage(s) added, {res['skipped']} skipped. "
              f"Saved in {res['library_file']}")
        return 0
    if c == "remove":
        p = library.get(ctx.paths, args.id)
        if p is not None and p.get("origin") == "builtin":
            print("Built-in passages can't be removed. To steer the choice use themes, e.g. "
                  "fde-coach config --set 'legato.themes=[\"speaking\",\"india\"]'")
            return 1
        print("Removed." if library.remove_user(ctx.paths, args.id) else f"No imported passage {args.id!r}.")
        return 0
    return 2


# --------------------------------------------------------------------------- parser

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="fde-coach", description=f"{APP_NAME} {__version__} ({SKILL_DIR})")
    p.add_argument("-v", "--verbose", action="store_true")
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("setup", help="create data folders, launcher and launchd schedule")
    s.add_argument("--time", help="daily run time HH:MM (default 05:30)")
    s.add_argument("--no-agents", action="store_true")
    s.add_argument("--no-warmup", action="store_true")
    s.set_defaults(func=cmd_setup)

    sub.add_parser("daily", help="scheduled run: build deck, open it, notify, ask to start").set_defaults(func=cmd_daily)

    s = sub.add_parser("session", help="record today's session now (QuickTime + slide show)")
    s.add_argument("--force", action="store_true", help="record again even if today is already recorded")
    s.add_argument("--detach", action="store_true", help="run in the background and return immediately")
    s.set_defaults(func=cmd_session)

    sub.add_parser("remind", help="reminder tick (launchd runs it every 15 minutes)").set_defaults(func=cmd_remind)

    s = sub.add_parser("generate", help="build today's questions + deck (keeps an existing one unless --replace)")
    s.add_argument("--source", choices=["auto", "claude", "bank"])
    s.add_argument("--replace", action="store_true", help="new questions for today (only before recording)")
    s.add_argument("--brief", help="extra guidance for Claude, e.g. 'healthcare customer, CISO audience'")
    s.add_argument("--open", action="store_true", help="open the deck afterwards")
    s.add_argument("--reveal", action="store_true", help="print the question texts (spoils the surprise)")
    s.set_defaults(func=cmd_generate)

    sub.add_parser("plan", help="JSON plan for authoring today's questions by hand").set_defaults(func=cmd_plan)

    s = sub.add_parser("build", help="build today's deck from a questions JSON file")
    s.add_argument("--questions", required=True)
    s.add_argument("--replace", action="store_true")
    s.set_defaults(func=cmd_build)

    sub.add_parser("open", help="open today's deck in PowerPoint").set_defaults(func=cmd_open)

    s = sub.add_parser("status", help="streak, today's state, uploads, schedule")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_status)

    s = sub.add_parser("history", help="past sessions and their questions")
    s.add_argument("--limit", type=int, default=14)
    s.add_argument("--reveal", action="store_true", help="also show today's questions before recording")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_history)

    s = sub.add_parser("complete", help="mark today as recorded when you recorded outside the automation")
    s.add_argument("--video", help="video path (default: newest video from today in the recordings folder)")
    s.add_argument("--no-video", action="store_true", help="you practised but have no usable video")
    s.add_argument("--note")
    s.set_defaults(func=cmd_complete)

    sub.add_parser("upload", help="upload pending recordings to YouTube (private)").set_defaults(func=cmd_upload)
    sub.add_parser("youtube-auth", help="connect YouTube once (opens a browser)").set_defaults(func=cmd_youtube_auth)
    sub.add_parser("calendar-auth", help="connect Google Calendar once for missed-practice alerts (opens a browser)"
                   ).set_defaults(func=cmd_calendar_auth)
    s = sub.add_parser("calendar-sync", help="bring the Google Calendar missed-practice alerts up to date")
    s.add_argument("--clear", action="store_true", help="delete all upcoming alerts created by this tool")
    s.set_defaults(func=cmd_calendar_sync)

    s = sub.add_parser("doctor", help="check installation, permissions and recent errors")
    s.add_argument("--warmup", action="store_true", help="trigger every macOS permission prompt now")
    s.set_defaults(func=cmd_doctor)

    sub.add_parser("install-agents", help="(re)install the launchd schedule").set_defaults(func=cmd_install_agents)
    sub.add_parser("uninstall-agents", help="remove the launchd schedule").set_defaults(func=cmd_uninstall_agents)

    s = sub.add_parser("config", help="show or change settings")
    s.add_argument("--set", action="append", metavar="KEY=VALUE",
                   help="e.g. daily_time=06:00  reminders.snooze_minutes=30  youtube.enabled=false")
    s.set_defaults(func=cmd_config)

    s = sub.add_parser("level", help="show or nudge the difficulty level")
    g = s.add_mutually_exclusive_group()
    g.add_argument("--up", action="store_true")
    g.add_argument("--down", action="store_true")
    g.add_argument("--reset", action="store_true")
    s.set_defaults(func=cmd_level)

    s = sub.add_parser("pronounce", help="daily pronunciation practice (pen method)")
    psub = s.add_subparsers(dest="pron_command", required=True)
    ps = psub.add_parser("session", help="record today's pronunciation session (audio only)")
    ps.add_argument("--force", action="store_true")
    ps.add_argument("--detach", action="store_true")
    ps.set_defaults(func=cmd_pronounce)
    psub.add_parser("daily", help="scheduled run: build the deck, notify, ask to start").set_defaults(func=cmd_pronounce)
    pg = psub.add_parser("generate", help="build today's paragraph + deck")
    pg.add_argument("--replace", action="store_true")
    pg.add_argument("--passage", metavar="ID", help="use this library passage (see: fde-coach library list)")
    pg.add_argument("--reveal", action="store_true", help="print the paragraph (spoils the cold read)")
    pg.set_defaults(func=cmd_pronounce)
    pst = psub.add_parser("status", help="pronunciation streak, today's state, words")
    pst.add_argument("--json", action="store_true")
    pst.set_defaults(func=cmd_pronounce)
    ph = psub.add_parser("history", help="past pronunciation sessions")
    ph.add_argument("--limit", type=int, default=14)
    ph.add_argument("--reveal", action="store_true", help="also show today's paragraph before recording")
    ph.add_argument("--json", action="store_true")
    ph.set_defaults(func=cmd_pronounce)
    pw = psub.add_parser("words", help="manage the hard-word pool")
    pw.add_argument("--add", action="append", metavar="WORD")
    pw.add_argument("--remove", action="append", metavar="WORD")
    pw.set_defaults(func=cmd_pronounce)
    psub.add_parser("upload", help="assemble + upload pending pronunciation videos").set_defaults(func=cmd_pronounce)

    s = sub.add_parser("legato", help="daily legato practice (smooth, connected speech)")
    lsub = s.add_subparsers(dest="leg_command", required=True)
    ls = lsub.add_parser("session", help="record today's legato session (audio only)")
    ls.add_argument("--force", action="store_true")
    ls.add_argument("--detach", action="store_true")
    ls.set_defaults(func=cmd_legato)
    lsub.add_parser("daily", help="scheduled run: build the deck, notify, ask to start").set_defaults(func=cmd_legato)
    lg = lsub.add_parser("generate", help="build today's passage + deck")
    lg.add_argument("--replace", action="store_true", help="a different passage (only before recording)")
    lg.add_argument("--passage", metavar="ID", help="use this library passage (see: fde-coach library list)")
    lg.add_argument("--reveal", action="store_true", help="print the passage (spoils the cold read)")
    lg.set_defaults(func=cmd_legato)
    lst = lsub.add_parser("status", help="legato streak and today's state")
    lst.add_argument("--json", action="store_true")
    lst.set_defaults(func=cmd_legato)
    lh = lsub.add_parser("history", help="past legato sessions")
    lh.add_argument("--limit", type=int, default=14)
    lh.add_argument("--json", action="store_true")
    lh.add_argument("--reveal", action="store_true", help="also show today's passage before recording")
    lh.set_defaults(func=cmd_legato)
    lsub.add_parser("upload", help="assemble + upload pending legato videos").set_defaults(func=cmd_legato)

    s = sub.add_parser("library", help="reading passages from free, public-domain books")
    lb = s.add_subparsers(dest="lib_command", required=True)
    bl = lb.add_parser("list", help="list passages")
    bl.add_argument("--theme")
    bl.add_argument("--level", type=int, choices=[1, 2, 3])
    bl.add_argument("--mine", action="store_true", help="only passages you imported")
    bl.add_argument("--json", action="store_true")
    bl.set_defaults(func=cmd_library)
    bs = lb.add_parser("show", help="show one passage with its source")
    bs.add_argument("id")
    bs.set_defaults(func=cmd_library)
    bg = lb.add_parser("import-gutenberg", help="add readable paragraphs from a Project Gutenberg book")
    bg.add_argument("book_id", type=int, help="the number in gutenberg.org/ebooks/NUMBER")
    bg.add_argument("--max", type=int, default=20, help="paragraphs to add, spread through the book (default 20)")
    bg.add_argument("--theme", help="label, e.g. speaking, story, reflection, india")
    bg.add_argument("--year", type=int, help="first publication year, for the credit line")
    bg.set_defaults(func=cmd_library)
    bf = lb.add_parser("import-file", help="add paragraphs from a text file you have the right to use")
    bf.add_argument("path")
    bf.add_argument("--author", required=True)
    bf.add_argument("--title", required=True)
    bf.add_argument("--year", type=int)
    bf.add_argument("--url", help="where the text comes from (shown in the credit)")
    bf.add_argument("--theme")
    bf.add_argument("--max", type=int, default=20)
    bf.set_defaults(func=cmd_library)
    br = lb.add_parser("remove", help="remove a passage you imported")
    br.add_argument("id")
    br.set_defaults(func=cmd_library)
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args) or 0)
    except KeyboardInterrupt:
        return 130
    except Exception as exc:  # noqa: BLE001 - log it and show a readable message
        import logging
        logging.getLogger("fdecoach").exception("command %s failed", args.command)
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
