#!/usr/bin/env python3
"""FDE Impromptu Coach - command line entry point.

Daily impromptu-speaking practice for the Forward Deployed Engineer role:
5 fresh questions in a Calibri/blue PowerPoint deck (60 s per slide, auto-advance),
recorded with QuickTime, uploaded to YouTube as a private video, with a streak
protected by escalating reminders.

Run `fde_coach.py --help` for commands. Python 3.9+.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import stat
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fdecoach import __version__  # noqa: E402
from fdecoach.config import APP_NAME, ENTRY_SCRIPT, SKILL_DIR, Paths, load_config, parse_hhmm, save_config  # noqa: E402


def _ctx(args):
    from fdecoach.app import Ctx
    return Ctx(verbose=getattr(args, "verbose", False))


def _print(obj) -> None:
    print(json.dumps(obj, indent=2, ensure_ascii=False))


def _sh(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _chmod_x(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


# --------------------------------------------------------------------------- commands

def cmd_setup(args) -> int:
    from fdecoach import questions, scheduler
    from fdecoach.state import Runtime
    ctx = _ctx(args)
    paths, cfg = ctx.paths, ctx.cfg
    claude = questions.resolve_claude(cfg)
    if claude and not cfg.get("claude_path"):
        cfg["claude_path"] = claude
    if args.time:
        parse_hhmm(args.time)
        cfg["daily_time"] = args.time
    save_config(paths, cfg)

    paths.bin_dir.mkdir(parents=True, exist_ok=True)
    wrapper = paths.bin_dir / "fde-coach"
    wrapper.write_text(
        "#!/bin/bash\n"
        f"# {APP_NAME} launcher (generated by setup)\n"
        f"export FDE_COACH_HOME={_sh(str(paths.root))}\n"
        f"exec {_sh(sys.executable)} {_sh(str(ENTRY_SCRIPT))} \"$@\"\n", encoding="utf-8")
    _chmod_x(wrapper)
    paths.start_command.write_text(
        "#!/bin/bash\n"
        f"# Double-click to record today's {APP_NAME} session.\n"
        f"{_sh(str(wrapper))} session\n"
        "echo\n"
        "echo \"Done. You can close this window.\"\n", encoding="utf-8")
    _chmod_x(paths.start_command)

    rt = Runtime(paths)
    rt.data["warmup_pending"] = not args.no_warmup
    rt.save()
    print(f"{APP_NAME} {__version__}")
    print(f"  data folder   : {paths.root}")
    print(f"  recordings    : {paths.recordings_dir(cfg, create=False)}")
    print(f"  claude CLI    : {claude or 'NOT FOUND - questions will come from the built-in bank'}")
    print(f"  launcher      : {wrapper}")
    print(f"  double-click  : {paths.start_command}")
    if not args.no_agents:
        # Agent reinstall is a fresh start: clear old error output so doctor
        # does not keep reporting errors from a previous install.
        for err_log in paths.logs.glob("*.err.log"):
            err_log.write_text("", encoding="utf-8")
        for line in scheduler.install(cfg, paths):
            print(f"  launchd       : {line}")
        print(f"  schedule      : daily at {cfg['daily_time']}, reminder checks every 15 minutes")
    return 0


def cmd_daily(args) -> int:
    from fdecoach import app
    res = app.daily(_ctx(args))
    _print(res)
    return 0 if res.get("ok") else 1


def cmd_session(args) -> int:
    from fdecoach import app
    ctx = _ctx(args)
    if args.detach:
        app.spawn_detached(["session"] + (["--force"] if args.force else []))
        print("Practice session started in the background: QuickTime recording + slide show "
              "(about 5 minutes). Check progress with: fde-coach status")
        return 0
    res = app.run_session(ctx, force=args.force)
    _print(res)
    return 0 if res.get("ok") else 1


def cmd_remind(args) -> int:
    from fdecoach import app
    print(app.remind(_ctx(args)))
    return 0


def cmd_generate(args) -> int:
    from fdecoach import app, macos
    ctx = _ctx(args)
    session, created = app.ensure_today(ctx, source=args.source, replace=args.replace, brief=args.brief or "")
    info = {
        "date": session["date"], "day_number": session["day_number"], "level": session["level"],
        "source": session["source"], "created": created, "deck": session["deck_path"],
        "categories": [f"{q.get('category_label')} (D{q.get('difficulty')})" for q in session["questions"]],
        "notes": session.get("notes", []),
        "questions": [q["text"] for q in session["questions"]] if args.reveal
        else "hidden to keep the surprise (see them after recording: fde-coach history)",
    }
    _print(info)
    if args.open:
        macos.powerpoint_open(Path(session["deck_path"]), ctx.cfg.get("presentation_app"))
    return 0


def cmd_plan(args) -> int:
    from fdecoach import app
    _print(app.authoring_plan(_ctx(args)))
    return 0


def cmd_build(args) -> int:
    from fdecoach import app
    ctx = _ctx(args)
    session, _ = app.ensure_today(ctx, questions_path=Path(args.questions).expanduser(), replace=args.replace)
    _print({"date": session["date"], "deck": session["deck_path"], "source": session["source"],
            "rejected_and_replaced_from_bank": session.get("notes", [])})
    return 0


def cmd_open(args) -> int:
    from fdecoach import app, macos
    ctx = _ctx(args)
    session, _ = app.ensure_today(ctx)
    macos.powerpoint_open(Path(session["deck_path"]), ctx.cfg.get("presentation_app"))
    print(session["deck_path"])
    return 0


def cmd_status(args) -> int:
    from fdecoach import app
    st = app.status(_ctx(args))
    if args.json:
        _print(st)
        return 0
    s = st["streak"]
    print(f"Streak: {s['current']} day(s)  |  best {s['best']}  |  total sessions {s['total']}  |  level {st['level']}/5")
    t = st["today"]
    if not t:
        print(f"Today ({st['date']}): no deck yet")
    else:
        state = "RECORDED" if t["recorded"] else "NOT RECORDED YET"
        print(f"Today ({st['date']}): Day {t['day_number']}  |  {state}  |  questions from {t['source']}")
        print(f"  deck : {t['deck']}")
        if t.get("video"):
            print(f"  video: {t['video']}")
        if t["recorded"]:
            yt = t.get("youtube") or {}
            print(f"  youtube: {yt.get('url') or yt.get('status')}")
    if st["next_reminder"]:
        extra = f" (snoozed until {st['snooze_until']})" if st["snooze_until"] else ""
        print(f"Next reminder: {st['next_reminder']}{extra}")
    if st["pending_uploads"]:
        print(f"Pending uploads: {', '.join(st['pending_uploads'])}")
    print(f"YouTube connected: {'yes' if st['youtube_configured'] else 'no (run: fde-coach youtube-auth)'}")
    if not st["calendar_configured"]:
        print("Google Calendar alerts: not connected (run: fde-coach calendar-auth)")
    elif st["calendar_today"]:
        state = {"created": "armed - alerts fire if you don't record",
                 "deleted": "cleared - recorded"}.get(st["calendar_today"], st["calendar_today"])
        print(f"Google Calendar alert today: {state}")
    print("Scheduler: " + ", ".join(f"{k.split('.')[-1]}={'on' if v else 'OFF'}" for k, v in st["agents"].items()))
    return 0


def cmd_history(args) -> int:
    from fdecoach import app
    rows = app.history_rows(_ctx(args), limit=args.limit, reveal_today=args.reveal)
    if args.json:
        _print(rows)
        return 0
    if not rows:
        print("No sessions yet.")
    for r in rows:
        mark = "\u2713" if r["recorded"] else "\u2717"
        print(f"{mark} {r['date']}  Day {r['day']}  L{r['level']}  youtube: {r['youtube']}  feedback: {r['feedback'] or '-'}")
        for q in r["questions"]:
            print(f"     - {q}")
    return 0


def cmd_complete(args) -> int:
    from fdecoach import app
    s = app.complete_manually(_ctx(args), Path(args.video) if args.video else None,
                              no_video=args.no_video, note=args.note or "")
    print(f"Marked {s.get('date')} as recorded ({s.get('video_path') or 'no video'}).")
    return 0


def cmd_upload(args) -> int:
    from fdecoach import app
    for line in app.upload_pending(_ctx(args), interactive=True):
        print(line)
    return 0


def cmd_youtube_auth(args) -> int:
    from fdecoach import app, youtube
    ctx = _ctx(args)
    print(youtube.authorize(ctx.paths))
    for line in app.upload_pending(ctx, interactive=True):
        print(line)
    return 0


def cmd_calendar_auth(args) -> int:
    from fdecoach import app, gcal
    ctx = _ctx(args)
    print(gcal.authorize(ctx.paths))
    for line in app.calendar_sync(ctx):
        print(line)
    return 0


def cmd_calendar_sync(args) -> int:
    from fdecoach import app
    for line in app.calendar_sync(_ctx(args), clear=args.clear):
        print(line)
    return 0


def cmd_doctor(args) -> int:
    from fdecoach import app, gcal, macos, questions, scheduler, youtube
    from fdecoach.state import Runtime
    ctx = _ctx(args)
    cfg, paths = ctx.cfg, ctx.paths
    problems = []

    def line(good: bool, label: str, detail: str = "") -> None:
        if not good:
            problems.append(label)
        print(f"[{'ok' if good else '!!'}] {label}{': ' + detail if detail else ''}")

    line(sys.version_info >= (3, 9), "Python", f"{sys.version.split()[0]} ({sys.executable})")
    for mod in ("pptx", "lxml", "googleapiclient", "google_auth_oauthlib"):
        try:
            __import__(mod)
            line(True, f"Python module {mod}")
        except ImportError:
            line(False, f"Python module {mod}", "missing - re-run install.sh")
    claude = questions.resolve_claude(cfg)
    if claude:
        try:
            ver = subprocess.run([claude, "--version"], capture_output=True, text=True, timeout=30).stdout.strip()
        except Exception as exc:  # noqa: BLE001
            ver = f"not runnable ({exc})"
        line(True, "Claude Code CLI", f"{claude} {ver}")
    else:
        line(False, "Claude Code CLI", "not found; set claude_path (the built-in bank still works)")
    line(macos.is_macos() or macos.dry_run(), "macOS", os.uname().sysname)
    line(macos.app_exists(cfg.get("presentation_app", "Microsoft PowerPoint")), "Microsoft PowerPoint installed")
    line(macos.app_exists("QuickTime Player"), "QuickTime Player installed")
    cam, mic = macos.has_camera(), macos.has_microphone()
    if cfg.get("recording", {}).get("mode") == "none":
        line(True, "Camera & microphone", "not needed (recording.mode=none: deck show only, no video)")
    else:
        line(cam and mic, "Camera & microphone",
             "found" if cam and mic else
             "not found - run sessions on a Mac with a camera, make camera-less practice the default "
             "(config --set recording.mode=none), or practise and mark the day: fde-coach complete --no-video")
    rec = paths.recordings_dir(cfg, create=False)
    if rec.exists():
        free = shutil.disk_usage(str(rec)).free / 1e9
        line(os.access(str(rec), os.W_OK) and free > 2, "Recordings folder", f"{rec} ({free:.0f} GB free)")
    else:
        line(False, "Recordings folder", f"{rec} does not exist yet (created on first session)")
    for label, loaded in scheduler.status().items():
        line(loaded, f"launchd agent {label}", "loaded" if loaded else "not loaded - run: fde-coach install-agents")
        # A loaded agent can still fail on every tick (e.g. macOS TCC blocks
        # launchd from reading the script); surface the last logged error.
        err = paths.logs / f"{label.split('.')[-1]}.err.log"
        if err.exists() and time.time() - err.stat().st_mtime < 86400:
            # agent stderr also carries INFO lines; only real errors matter
            errors = [l for l in err.read_text(encoding="utf-8", errors="replace").splitlines()
                      if ("ERROR" in l or "Traceback" in l or "Errno" in l)]
            if errors:
                msg = errors[-1]
                line(False, f"agent {label} error log", msg[:120] + ("…" if len(msg) > 120 else ""))
    if cfg.get("youtube", {}).get("enabled", True):
        line(paths.client_secret.exists(), "YouTube OAuth client file", str(paths.client_secret))
        configured = youtube.is_configured(paths)
        line(configured, "YouTube authorized", "yes" if configured else "run: fde-coach youtube-auth")
    gc = cfg.get("google_calendar", {})
    if gc.get("enabled", True):
        connected = gcal.is_configured(paths)
        line(connected, "Google Calendar missed-practice alerts",
             f"on (event {gc.get('event_time')}, alerts {', '.join(gc.get('popup_times') or [])})" if connected
             else "run: fde-coach calendar-auth")
    rt = Runtime(paths)
    if rt.data.get("warmup_results"):
        print(f"     background permission check ({rt.data.get('warmup_at')}): " + "; ".join(rt.data["warmup_results"]))
    if args.warmup:
        print("Permission warm-up from this terminal (click OK/Allow on every macOS prompt):")
        for r in app.run_warmup(ctx):
            print("   " + r)
        app.update_runtime(ctx, lambda r: r.data.update(warmup_pending=True))
        scheduler.kickstart(scheduler.REMIND_LABEL)
        print("Also triggered the background agent so macOS asks for its own permissions now - approve those too.")
    log_file = paths.logs / "fde_coach.log"
    if log_file.exists():
        tail = log_file.read_text(encoding="utf-8", errors="ignore").splitlines()[-400:]
        errors = [ln for ln in tail if " ERROR " in ln or " WARNING " in ln]
        if errors:
            print("Recent warnings/errors:")
            for ln in errors[-8:]:
                print("   " + ln[:220])
    print("All good." if not problems else f"{len(problems)} item(s) need attention.")
    return 0 if not problems else 1


def cmd_install_agents(args) -> int:
    from fdecoach import scheduler
    ctx = _ctx(args)
    for line in scheduler.install(ctx.cfg, ctx.paths):
        print(line)
    return 0


def cmd_uninstall_agents(args) -> int:
    from fdecoach import scheduler
    for line in scheduler.uninstall():
        print(line)
    return 0


def _coerce(value: str):
    try:
        return json.loads(value)
    except ValueError:
        return value


def cmd_config(args) -> int:
    from fdecoach import scheduler
    _ctx(args)
    paths = Paths()
    user = json.loads(paths.config.read_text(encoding="utf-8")) if paths.config.exists() else {}
    if args.set:
        reinstall = False
        for item in args.set:
            key, sep, raw = item.partition("=")
            if not key or not sep:
                print(f"bad --set {item!r}; use key=value (dotted keys for nested values, JSON for lists/bools)")
                return 2
            value = _coerce(raw)
            if key == "daily_time":
                parse_hhmm(str(value))
                reinstall = True
            node = user
            parts = key.split(".")
            for part in parts[:-1]:
                node = node.setdefault(part, {})
            node[parts[-1]] = value
        save_config(paths, user)
        print("Saved.")
        if reinstall:
            for line in scheduler.install(load_config(paths), paths):
                print(line)
    _print(load_config(paths))
    return 0


def cmd_level(args) -> int:
    from fdecoach import app
    from fdecoach.state import level_for, today
    ctx = _ctx(args)

    def change(rt) -> None:
        cur = 0 if args.reset else int(rt.data.get("level_adjust", 0)) + (1 if args.up else -1 if args.down else 0)
        rt.data["level_adjust"] = max(-4, min(4, cur))

    if args.up or args.down or args.reset:
        app.update_runtime(ctx, change)
    lvl = level_for(ctx.history(), ctx.cfg, ctx.runtime(), today())
    print(f"Level for the next new deck: {lvl} of 5 (manual adjustment {int(ctx.runtime().data.get('level_adjust', 0)):+d}). "
          "An existing deck keeps its level unless you run: fde-coach generate --replace")
    return 0


# --------------------------------------------------------------------------- parser

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="fde-coach", description=f"{APP_NAME} {__version__} ({SKILL_DIR})")
    p.add_argument("-v", "--verbose", action="store_true")
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("setup", help="create data folders, launcher and launchd schedule")
    s.add_argument("--time", help="daily run time HH:MM (default 05:30)")
    s.add_argument("--no-agents", action="store_true")
    s.add_argument("--no-warmup", action="store_true")
    s.set_defaults(func=cmd_setup)

    sub.add_parser("daily", help="scheduled run: build deck, open it, notify, ask to start").set_defaults(func=cmd_daily)

    s = sub.add_parser("session", help="record today's session now (QuickTime + slide show)")
    s.add_argument("--force", action="store_true", help="record again even if today is already recorded")
    s.add_argument("--detach", action="store_true", help="run in the background and return immediately")
    s.set_defaults(func=cmd_session)

    sub.add_parser("remind", help="reminder tick (launchd runs it every 15 minutes)").set_defaults(func=cmd_remind)

    s = sub.add_parser("generate", help="build today's questions + deck (keeps an existing one unless --replace)")
    s.add_argument("--source", choices=["auto", "claude", "bank"])
    s.add_argument("--replace", action="store_true", help="new questions for today (only before recording)")
    s.add_argument("--brief", help="extra guidance for Claude, e.g. 'healthcare customer, CISO audience'")
    s.add_argument("--open", action="store_true", help="open the deck afterwards")
    s.add_argument("--reveal", action="store_true", help="print the question texts (spoils the surprise)")
    s.set_defaults(func=cmd_generate)

    sub.add_parser("plan", help="JSON plan for authoring today's questions by hand").set_defaults(func=cmd_plan)

    s = sub.add_parser("build", help="build today's deck from a questions JSON file")
    s.add_argument("--questions", required=True)
    s.add_argument("--replace", action="store_true")
    s.set_defaults(func=cmd_build)

    sub.add_parser("open", help="open today's deck in PowerPoint").set_defaults(func=cmd_open)

    s = sub.add_parser("status", help="streak, today's state, uploads, schedule")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_status)

    s = sub.add_parser("history", help="past sessions and their questions")
    s.add_argument("--limit", type=int, default=14)
    s.add_argument("--reveal", action="store_true", help="also show today's questions before recording")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_history)

    s = sub.add_parser("complete", help="mark today as recorded when you recorded outside the automation")
    s.add_argument("--video", help="video path (default: newest video from today in the recordings folder)")
    s.add_argument("--no-video", action="store_true", help="you practised but have no usable video")
    s.add_argument("--note")
    s.set_defaults(func=cmd_complete)

    sub.add_parser("upload", help="upload pending recordings to YouTube (private)").set_defaults(func=cmd_upload)
    sub.add_parser("youtube-auth", help="connect YouTube once (opens a browser)").set_defaults(func=cmd_youtube_auth)
    sub.add_parser("calendar-auth", help="connect Google Calendar once for missed-practice alerts (opens a browser)"
                   ).set_defaults(func=cmd_calendar_auth)
    s = sub.add_parser("calendar-sync", help="bring the Google Calendar missed-practice alerts up to date")
    s.add_argument("--clear", action="store_true", help="delete all upcoming alerts created by this tool")
    s.set_defaults(func=cmd_calendar_sync)

    s = sub.add_parser("doctor", help="check installation, permissions and recent errors")
    s.add_argument("--warmup", action="store_true", help="trigger every macOS permission prompt now")
    s.set_defaults(func=cmd_doctor)

    sub.add_parser("install-agents", help="(re)install the launchd schedule").set_defaults(func=cmd_install_agents)
    sub.add_parser("uninstall-agents", help="remove the launchd schedule").set_defaults(func=cmd_uninstall_agents)

    s = sub.add_parser("config", help="show or change settings")
    s.add_argument("--set", action="append", metavar="KEY=VALUE",
                   help="e.g. daily_time=06:00  reminders.snooze_minutes=30  youtube.enabled=false")
    s.set_defaults(func=cmd_config)

    s = sub.add_parser("level", help="show or nudge the difficulty level")
    g = s.add_mutually_exclusive_group()
    g.add_argument("--up", action="store_true")
    g.add_argument("--down", action="store_true")
    g.add_argument("--reset", action="store_true")
    s.set_defaults(func=cmd_level)
    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return int(args.func(args) or 0)
    except KeyboardInterrupt:
        return 130
    except Exception as exc:  # noqa: BLE001 - log it and show a readable message
        import logging
        logging.getLogger("fdecoach").exception("command %s failed", args.command)
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
